In [14]:
# Third party modules
import numpy
from PIL import Image


def get_image(image_path):
    """Get a numpy array of an image so that one can access values[x][y]."""
    image = Image.open(image_path, "r")
    width, height = image.size
    pixel_values = list(image.getdata())
    if image.mode == "RGB":
        channels = 3
    elif image.mode == "L":
        channels = 1
    else:
        print("Unknown mode: %s" % image.mode)
        return None
    pixel_values = numpy.array(pixel_values).reshape((width, height, channels))
    return pixel_values


image = get_image("lena.jpg")

print(image)
print(image.shape)

[[[225 138 128]
  [224 137 127]
  [223 136 126]
  ...
  [234 146 126]
  [220 129 110]
  [197 104  86]]

 [[222 138 127]
  [224 137 127]
  [224 137 127]
  ...
  [235 150 130]
  [218 131 112]
  [189 102  83]]

 [[222 138 127]
  [224 137 127]
  [225 138 128]
  ...
  [230 148 127]
  [215 133 112]
  [190 105  85]]

 ...

 [[ 82  21  55]
  [ 81  20  54]
  [ 92  28  62]
  ...
  [175  71  82]
  [175  68  78]
  [175  65  74]]

 [[ 80  18  55]
  [ 81  20  54]
  [ 94  33  67]
  ...
  [177  69  82]
  [182  70  82]
  [183  72  81]]

 [[ 81  19  56]
  [ 83  21  58]
  [ 96  35  69]
  ...
  [178  68  81]
  [183  71  83]
  [188  74  84]]]
(512, 512, 3)
